version: '3.8'
services:
    caddy:
        # TODO see "Docker Compose example" section:
        # https://hub.docker.com/_/caddy
        image: caddy
        restart: unless-stopped
        ports:
            - 80:80
        # TODO add caddy config to `resources/Caddyfile`
        #volumes:
            #- ./resources/Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - komga
            - nextcloud
    komga:
        # TODO see:
        # https://komga.org/docs/installation/docker/#docker-compose
        image: gotson/komga
        container_name: komga
        ports:
            # TODO this maps the container's port to the host machine.
            # This is enabled for debugging, once removed then only caddy will see this service
            - 25600:25600
        user: 1000:1000
    nextcloud:
        # TODO see:
        # https://github.com/nextcloud/docker?tab=readme-ov-file#running-this-image-with-docker-compose
        image: nextcloud
        restart: unless-stopped
        ports:
            # TODO this maps the container's port to the host machine.
            # This is enabled for debugging, once removed then only caddy will see this service
            - 8080:8080
        # TODO define a `nextcloud` Docker volume that this container can use
        #volumes:
        #    - nextcloud:/var/www/html
        #environment:
        #   - MYSQL_PASSWORD=
        #   - MYSQL_DATABASE=nextcloud
        #   - MYSQL_USER=nextcloud
        #   - MYSQL_HOST=db
